import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} antialiased`}>
                <header className="w-full p-4 border-b mb-4 flex justify-center">
                    <nav className="flex gap-4 items-center">
                        <Link href="/">Home</Link>
                        <Link href="/reception">Reception</Link>
                        <Link href="/room">Room</Link>
                        <Link href="/gallery">Gallery</Link>
                    </nav>
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
